spring.application.name=jobly-backend

spring.datasource.url=jdbc:postgresql://localhost:2345/jobly_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Scheduler enabled
spring.main.allow-bean-definition-overriding=true